# Generated by Django 4.2.3 on 2023-10-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_place',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
