# Generated by Django 4.2.3 on 2023-10-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_book_publication_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_place',
        ),
    ]
